# conda env create --file environment.yml
# mamba env create --file environment.yml
name: project_snl_regression

channels:
  - conda-forge
  - defaults
dependencies:
  - python= 3.10
  - numpy
  - matplotlib  
  - pandas
  - pyprojroot
  - pip
  - jupyter
  - jupyterlab

  